### ISSUE TITLE
Shovel digiscanner prob

### ISSUE THREAD

**Issue by AdiTechs10** [christikat/glow_treasure#2]
![image](https://user-images.githubusercontent.com/86138741/211191119-b0310c56-c510-4244-a0a9-7c53943d6853.png)

The digiscanner does not scan a close treasure. it just remain blank bar also when i tried digging on the exact location the treasure won't come up

**Comment by christikat** [comment]
Can you double check and make sure your at the correct coords for that scanner? The script randomly picks one of the coords from the config and sets it as the treasure location.

**Comment by AdiTechs10** [comment]
> Can you double check and make sure your at the correct coords for that scanner? The script randomly picks one of the coords from the config and sets it as the treasure location.

How do i see the coordinates that the scanner gives?

**Comment by christikat** [comment]
You can check in your database where the player's inventory is saved. Or in the script you can add SetEntityCoords(PlayerPedId(), targetCoords.x, targetCoords.y, targetCoords.z) in the toggleScanner event in client.lua. And that will tp directly to the coords.

**Comment by AdiTechs10** [comment]
> You can check in your database where the player's inventory is saved. Or in the script you can add SetEntityCoords(PlayerPedId(), targetCoords.x, targetCoords.y, targetCoords.z) in the toggleScanner event in client.lua. And that will tp directly to the coords.

it works already though my only issue is that, i need to re use my digiscanner so it scans another bar because it doesnt change real time

**Comment by christikat** [comment]
Can you take a video of it? Are there no colour changes as well as the number of bars remaining the same? Are you moving past the distance threshold for the bars to update. You can see the thresholds in the updateScaleformBars function.  And for optimization reasons, its coded to only update when you use right click and aim the scanner.

**Comment by AdiTechs10** [comment]
I will take a video of it, the color changes only when u reuse the scanner. the number of bar are not changing real time even though im on the radius of where the treasure is, I still need to reuse the scanner in order to change bars/color

**Comment by jnccloud** [comment]
@christikat this is not a problem with the script. It is most likely because @AdiTechs10 has a stop controller aim assist thread running. This is what I did to fix mine, I added checks to stop ignore the digiscanner.

```lua
-- Disable Aim Assist on Controllers
CreateThread(function()
    local sleep = 1000
    while true do
        if IsPedArmed(PlayerPedId(), 2) or IsPedArmed(PlayerPedId(), 4) then
            local weapon = GetSelectedPedWeapon(PlayerPedId())
            if weapon ~= `WEAPON_DIGISCANNER` then
                SetPlayerLockon(PlayerId(), false)
                sleep = 0
            end
        else
            local weapon = GetSelectedPedWeapon(PlayerPedId())
            if weapon ~= `WEAPON_DIGISCANNER` then
                SetPlayerLockon(PlayerId(), true)
                sleep = 1000
            end
        end
        Wait(sleep)
    end
end)
```

**Comment by AdiTechs10** [comment]
that sums it up i have a anti aim assist on my server

**Comment by AdiTechs10** [comment]
Solved

**Comment by SpringVisual** [comment]
![image](https://github.com/christikat/glow_treasure/assets/83093805/19a5a75a-bb90-4e68-b2c9-c45412756f0a)
when im using the item.. what i need to do ?
